;; This file is automatically generated by the multiple-cursors
;; extension.
;; It keeps track of your preferences for running commands with
;; multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        isearch-printing-char
        ))

(setq mc/cmds-to-run-once
      '(
        isearch-forward-regexp
        isearch-other-control-char
        js2-mode-match-curly
        js2-mode-match-paren
        ))
